import { getPages } from "@/sanity/sanity-utils";
import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import "../globals.css";
import Header from "@/app/components/header";

const font = Work_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next.js Portfolio",
  description: "Generated by Next + Sanity",
};

export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pages = await getPages();

  return (
    <html lang='en'>
      <head>
        <link
          rel='stylesheet'
          type='text/css'
          href='https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css'
        />
      </head>

      <body className={`flex flex-col min-h-screen ${font.className}`}>
        <Header pages={pages} />
        <main className='ml-[150px] mr-20 mt-10'>{children}</main>
        <footer className='flex items-baseline justify-center px-[28px] py-[56px] mt-auto'>
          <p>&copy; 2024 Vadym Popov </p>
        </footer>
      </body>
    </html>
  );
}
