import { getPages } from "@/sanity/sanity-utils";
import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import "../globals.css";
import Header from "@/app/components/header";
import NextTopLoader from "nextjs-toploader";
import { Providers } from "./providers";

const font = Work_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vadym | Frontend Dev",
  description: "Generated by Next + Sanity",
};

export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pages = await getPages();

  return (
    <html lang='en' suppressHydrationWarning>
      <head>
        <link
          rel='stylesheet'
          type='text/css'
          href='https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css'
        />
      </head>

      <body className={`flex flex-col min-h-screen ${font.className}`}>
        <Providers>
          <NextTopLoader
            color='#3b82f6'
            initialPosition={0.08}
            crawlSpeed={200}
            height={3}
            crawl={true}
            showSpinner={false}
            easing='easeIn'
            speed={200}
            shadow='0 0 10px #3b82f6, 0 0 5px #3b82f6'
          />
          <Header pages={pages} />
          <main className='ml-[150px] mr-24 mt-20'>{children}</main>
          <footer className='flex items-baseline justify-center px-[28px] py-[56px] mt-auto'>
            <p>&copy; 2024 Vadym Popov </p>
          </footer>
        </Providers>
      </body>
    </html>
  );
}
